<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-HSQVMDT" failures="1" tests="1" name="timeOut(failed)" time="0.245" errors="0" timestamp="11 Dec 2020 03:32:48 GMT">
  <testcase classname="TestNG_Examples.timeOut" name="testcase1" time="0.222">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNG_Examples.timeOut.testcase1() didn&amp;apos;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG_Examples.timeOut.testcase1() didn't finish within the time-out 200
	at java.base@15.0.1/java.lang.invoke.MethodHandleNatives.linkMethodImpl(MethodHandleNatives.java:471)
	at java.base@15.0.1/java.lang.invoke.MethodHandleNatives.linkMethod(MethodHandleNatives.java:463)
	at java.base@15.0.1/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
	at java.base@15.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@15.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestNG_Examples.timeOut" name="testcase3" time="0.0">
    <ignored/>
  </testcase> <!-- testcase3 -->
  <testcase classname="TestNG_Examples.timeOut" name="testcase2" time="0.0">
    <ignored/>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- timeOut(failed) -->
